# Generated by Django 4.2.1 on 2024-04-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_studentresulttest1_studentresulttest2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test1_marks', models.FloatField(blank=True, default=0, null=True)),
                ('test2_marks', models.FloatField(blank=True, default=0, null=True)),
                ('UE_marks', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentresulttest2',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentresulttest2',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='studentresultue',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentresultue',
            name='subject_id',
        ),
        migrations.DeleteModel(
            name='StudentResultTest1',
        ),
        migrations.DeleteModel(
            name='StudentResultTest2',
        ),
        migrations.DeleteModel(
            name='StudentResultUE',
        ),
    ]
