# Generated by Django 4.2.1 on 2024-04-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_studentresult_remove_studentresulttest2_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18)),
                ('address', models.CharField(choices=[('U', 'Urban'), ('R', 'Rural')], default='Unspecified', max_length=1)),
                ('medu', models.IntegerField(choices=[(0, 'None'), (1, 'Primary education (4th grade)'), (2, '5th to 9th grade'), (3, 'Secondary education'), (4, 'Higher education')], default=0)),
                ('fedu', models.IntegerField(choices=[(0, 'None'), (1, 'Primary education (4th grade)'), (2, '5th to 9th grade'), (3, 'Secondary education'), (4, 'Higher education')], default=0)),
                ('traveltime', models.IntegerField(choices=[(1, '1 hours'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours')], default=0)),
                ('studytime', models.IntegerField(choices=[(1, '1 hours'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours'), (5, '5 hours'), (6, '6 hours'), (7, '7 hours'), (8, '8 hours'), (9, '9 hours'), (10, '10 hours')], default=0)),
                ('failures', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4 or more')], default=0)),
                ('famrel', models.IntegerField(default=0)),
                ('freetime', models.IntegerField(default=0)),
                ('goout', models.IntegerField(default=0)),
                ('dalc', models.IntegerField(default=0)),
                ('walc', models.IntegerField(default=0)),
                ('health', models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Very good')], default=0)),
                ('absences', models.IntegerField(default=0)),
                ('g1', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0, verbose_name='First period grade')),
                ('g2', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0, verbose_name='Second period grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student_management_app.students')),
            ],
        ),
    ]
