# Generated by Django 4.2.1 on 2024-04-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_studentperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='absences',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='address',
            field=models.CharField(blank=True, choices=[('U', 'Urban'), ('R', 'Rural')], default='Unspecified', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='dalc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='failures',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4 or more')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='famrel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='fedu',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Primary education (4th grade)'), (2, '5th to 9th grade'), (3, 'Secondary education'), (4, 'Higher education')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='freetime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='goout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='health',
            field=models.IntegerField(blank=True, choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Very good')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='medu',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Primary education (4th grade)'), (2, '5th to 9th grade'), (3, 'Secondary education'), (4, 'Higher education')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='studytime',
            field=models.IntegerField(blank=True, choices=[(1, '1 hours'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours'), (5, '5 hours'), (6, '6 hours'), (7, '7 hours'), (8, '8 hours'), (9, '9 hours'), (10, '10 hours')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='traveltime',
            field=models.IntegerField(blank=True, choices=[(1, '1 hours'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='walc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
