# Generated by Django 4.2.1 on 2024-04-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='child',
        ),
    ]
