# Generated by Django 4.2.1 on 2024-04-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_remove_parents_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='child',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students'),
        ),
    ]
