# Generated by Django 4.2.1 on 2024-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='total_CA',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
