# Generated by Django 4.2.1 on 2024-04-25 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_studentresult_total_ca'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test1_marks', models.FloatField(blank=True, default=0, null=True)),
                ('test2_marks', models.FloatField(blank=True, default=0, null=True)),
                ('UE_prediction', models.FloatField(blank=True, default=0, null=True)),
                ('total_CA', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='student_management_app.studentresult')),
            ],
        ),
    ]
