# Generated by Django 4.2.1 on 2024-04-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_predictionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodel',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='student_management_app.studentresult'),
        ),
    ]
