# Generated by Django 4.1.4 on 2024-05-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0016_alter_predictionmodel_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('marks', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
